version: "3"
services:
  postgres:
    image: postgres:16
    restart: always
    container_name: money-postgres
    environment:
      - POSTGRES_USER=money-db-user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=money-db
    ports:
      - '5432:5432'


#    volumes:
#      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
